//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tei-c.org/ns/1.0", IsNullable=false)]
public partial class p {
    
    private @ref[] refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ref", IsNullable=true)]
    public @ref[] @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tei-c.org/ns/1.0", IsNullable=true)]
public partial class @ref {
    
    private string targetField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tei-c.org/ns/1.0", IsNullable=false)]
public partial class TEI {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(@ref[]))]
    [System.Xml.Serialization.XmlElementAttribute("ref", typeof(@ref), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("teiHeader", typeof(TEITeiHeader))]
    [System.Xml.Serialization.XmlElementAttribute("text", typeof(TEIText))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeader {
    
    private TEITeiHeaderFileDesc[] fileDescField;
    
    private @ref[][][][] encodingDescField;
    
    private TEITeiHeaderRevisionDescChange[][] revisionDescField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fileDesc")]
    public TEITeiHeaderFileDesc[] fileDesc {
        get {
            return this.fileDescField;
        }
        set {
            this.fileDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("projectDesc", typeof(@ref[][]), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("p", typeof(@ref[]), IsNullable=false, NestingLevel=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ref", typeof(@ref), NestingLevel=2)]
    public @ref[][][][] encodingDesc {
        get {
            return this.encodingDescField;
        }
        set {
            this.encodingDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("change", typeof(TEITeiHeaderRevisionDescChange), IsNullable=false)]
    public TEITeiHeaderRevisionDescChange[][] revisionDesc {
        get {
            return this.revisionDescField;
        }
        set {
            this.revisionDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDesc {
    
    private string extentField;
    
    private TEITeiHeaderFileDescTitleStmt[] titleStmtField;
    
    private TEITeiHeaderFileDescEditionStmt[] editionStmtField;
    
    private TEITeiHeaderFileDescPublicationStmt[] publicationStmtField;
    
    private TEITeiHeaderFileDescNotesStmtNote[][] notesStmtField;
    
    private @ref[][][] sourceDescField;
    
    /// <remarks/>
    public string extent {
        get {
            return this.extentField;
        }
        set {
            this.extentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("titleStmt")]
    public TEITeiHeaderFileDescTitleStmt[] titleStmt {
        get {
            return this.titleStmtField;
        }
        set {
            this.titleStmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("editionStmt")]
    public TEITeiHeaderFileDescEditionStmt[] editionStmt {
        get {
            return this.editionStmtField;
        }
        set {
            this.editionStmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("publicationStmt")]
    public TEITeiHeaderFileDescPublicationStmt[] publicationStmt {
        get {
            return this.publicationStmtField;
        }
        set {
            this.publicationStmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("note", typeof(TEITeiHeaderFileDescNotesStmtNote))]
    public TEITeiHeaderFileDescNotesStmtNote[][] notesStmt {
        get {
            return this.notesStmtField;
        }
        set {
            this.notesStmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("p", typeof(@ref[]), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ref", typeof(@ref), NestingLevel=1)]
    public @ref[][][] sourceDesc {
        get {
            return this.sourceDescField;
        }
        set {
            this.sourceDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDescTitleStmt {
    
    private string titleField;
    
    private TEITeiHeaderFileDescTitleStmtRespStmt[] respStmtField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("respStmt")]
    public TEITeiHeaderFileDescTitleStmtRespStmt[] respStmt {
        get {
            return this.respStmtField;
        }
        set {
            this.respStmtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDescTitleStmtRespStmt {
    
    private string respField;
    
    private string nameField;
    
    /// <remarks/>
    public string resp {
        get {
            return this.respField;
        }
        set {
            this.respField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDescEditionStmt {
    
    private string editionField;
    
    /// <remarks/>
    public string edition {
        get {
            return this.editionField;
        }
        set {
            this.editionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDescPublicationStmt {
    
    private string publisherField;
    
    private TEITeiHeaderFileDescPublicationStmtAvailability[] availabilityField;
    
    private @ref[][] pubPlaceField;
    
    /// <remarks/>
    public string publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("availability")]
    public TEITeiHeaderFileDescPublicationStmtAvailability[] availability {
        get {
            return this.availabilityField;
        }
        set {
            this.availabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ref", typeof(@ref))]
    public @ref[][] pubPlace {
        get {
            return this.pubPlaceField;
        }
        set {
            this.pubPlaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDescPublicationStmtAvailability {
    
    private @ref[][] pField;
    
    private string statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ref", typeof(@ref))]
    public @ref[][] p {
        get {
            return this.pField;
        }
        set {
            this.pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderFileDescNotesStmtNote {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderRevisionDescChange {
    
    private string dateField;
    
    private string nameField;
    
    private TEITeiHeaderRevisionDescChangeListItem[][] listField;
    
    private string whenField;
    
    private string whoField;
    
    private string nField;
    
    /// <remarks/>
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(TEITeiHeaderRevisionDescChangeListItem))]
    public TEITeiHeaderRevisionDescChangeListItem[][] list {
        get {
            return this.listField;
        }
        set {
            this.listField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string when {
        get {
            return this.whenField;
        }
        set {
            this.whenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string who {
        get {
            return this.whoField;
        }
        set {
            this.whoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string n {
        get {
            return this.nField;
        }
        set {
            this.nField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITeiHeaderRevisionDescChangeListItem {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEIText {
    
    private TEITextBodyEntry[][] bodyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(TEITextBodyEntry), IsNullable=false)]
    public TEITextBodyEntry[][] body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITextBodyEntry {
    
    private TEITextBodyEntryForm[] formField;
    
    private TEITextBodyEntryGramGrp[] gramGrpField;
    
    private TEITextBodyEntrySense[] senseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("form")]
    public TEITextBodyEntryForm[] form {
        get {
            return this.formField;
        }
        set {
            this.formField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gramGrp")]
    public TEITextBodyEntryGramGrp[] gramGrp {
        get {
            return this.gramGrpField;
        }
        set {
            this.gramGrpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sense")]
    public TEITextBodyEntrySense[] sense {
        get {
            return this.senseField;
        }
        set {
            this.senseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITextBodyEntryForm {
    
    private string orthField;
    
    private string pronField;
    
    /// <remarks/>
    public string orth {
        get {
            return this.orthField;
        }
        set {
            this.orthField = value;
        }
    }
    
    /// <remarks/>
    public string pron {
        get {
            return this.pronField;
        }
        set {
            this.pronField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITextBodyEntryGramGrp {
    
    private string posField;
    
    /// <remarks/>
    public string pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITextBodyEntrySense {
    
    private TEITextBodyEntrySenseCit[] citField;
    
    private string nField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cit")]
    public TEITextBodyEntrySenseCit[] cit {
        get {
            return this.citField;
        }
        set {
            this.citField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string n {
        get {
            return this.nField;
        }
        set {
            this.nField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tei-c.org/ns/1.0")]
public partial class TEITextBodyEntrySenseCit {
    
    private string quoteField;
    
    private string typeField;
    
    /// <remarks/>
    public string quote {
        get {
            return this.quoteField;
        }
        set {
            this.quoteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
